# Introdução à Ciência de Dados - UFPB
Professor: Yuri Malheiros

## NumPy

Implemente a função `distance` abaixo. Ela deve receber dois pontos e retornar a distância euclidiana entre eles. Cada ponto é representado por um array do NumPy, por exemplo, `p1 = np.array([2,4])` representa o ponto com coordenadas x=2 e y=2.

In [3]:
import numpy as np
import math 

def distance(p1, p2):
    """
    >>> distance(np.array([0,0]), np.array([1,1]))
    1.4142135623730951
    
    >>> distance(np.array([1,2]), np.array([3,4]))
    2.8284271247461903
    
    >>> distance(np.array([5,2]), np.array([-2,-1]))
    7.615773105863909
    """

    # ADICIONE O SEU CÓDIGO AQUI
    diferença = p1 - p2
    
    quadrado_dif = np.dot(diferença, diferença)
    
    distancia = math.sqrt(quadrado_dif)
    
    return distancia

print (distance(np.array([0,0]), np.array([1,1])))
print (distance(np.array([1,2]), np.array([3,4])))
print (distance(np.array([5,2]), np.array([-2,-1])))


1.4142135623730951
2.8284271247461903
7.615773105863909


Implemente a função `n_distances` abaixo. Ela recebe um ponto (`p1`), como um array do NumPy, e uma lista de pontos (`points`), uma matriz do NumPy, onde cada linha representa um ponto.

Esta função deve retornar a distância de `p1` para todos os pontos da matriz `points`. O retorno também é uma matriz, onde cada linha tem a distância de `p1` para o ponto daquela linha.

In [109]:
import numpy as np
import math

def n_distances(p1, points):
    
    """
    >>> n_distances(np.array([0,0]), np.array([[1,1]]))
    array([1.41421356])
    
    >>> n_distances('np.array([0,0]), np.array([[1,1], [2,2]]'))
    array([1.41421356, 2.82842712])
    
    >>> n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
    """
    
    # ADICIONE O SEU CÓDIGO AQUI
    
    diferença = p1 - points
    
    a = np.array([])
    
    
    for i in range(len(diferença)):
        raiz =  math.sqrt(np.dot(diferença[i], diferença[i]))
        print(raiz)
        #Eu não sei porque o np.append não está adicionando o valor no array vazio "a", pra mim a lógica está certa e isso não faz sentido
        np.append(a,raiz)
    
    print (a)
            

n_distances(np.array([0,0]), np.array([[1,1]]))
n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
                   

        

1.4142135623730951
[]
1.4142135623730951
2.8284271247461903
[]
3.605551275463989
1.4142135623730951
4.0
9.055385138137417
7.615773105863909
[]


## Teste

In [110]:
import doctest

doctest.testmod(verbose=True)

Trying:
    distance(np.array([0,0]), np.array([1,1]))
Expecting:
    1.4142135623730951
ok
Trying:
    distance(np.array([1,2]), np.array([3,4]))
Expecting:
    2.8284271247461903
ok
Trying:
    distance(np.array([5,2]), np.array([-2,-1]))
Expecting:
    7.615773105863909
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1]]))
Expecting:
    array([1.41421356])
**********************************************************************
File "__main__", line 6, in __main__.n_distances
Failed example:
    n_distances(np.array([0,0]), np.array([[1,1]]))
Expected:
    array([1.41421356])
Got:
    1.4142135623730951
    []
Trying:
    n_distances('np.array([0,0]), np.array([[1,1], [2,2]]'))
Expecting:
    array([1.41421356, 2.82842712])
**********************************************************************
File "__main__", line 9, in __main__.n_distances
Failed example:
    n_distances('np.array([0,0]), np.array([[1,1], [2,2]]'))
Exception raised:
    Traceback (most recent call last):
 

TestResults(failed=3, attempted=6)